# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: push Githubpage

on:  # 触发时机
  workflow_dispatch: # 手动触发
  push: # 代码提交触发
    branches: # 在哪个分支
      - master	# 在main分支
  # pull_request: # PR提交时触发

jobs: # 工作流
  first-job: # 工作名称
    runs-on: ubuntu-latest # 运行在哪个环境中
    steps: # 步骤
      - name: Checkout # 步骤名
        uses: actions/checkout@v3 # 使用market上的脚本包
      - name: Setup node
        uses: actions/setup-node@v3
        with: # 设定参数
          node-version: 18.x
      - name: install
        run: npm install
      - name: build
        run: npm run build
      - name: push
        run: sh deploy.sh
