# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: add_page_one

on:  # 触发时机
  workflow_dispatch: # 手动触发
  push: # 代码提交触发
    branches: # 在哪个分支
      - master	# 在main分支
  # pull_request: # PR提交时触发
jobs:
  blog-catch-and-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codes
        uses: actions/checkout@v3 # 使用market上的脚本包

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install and run
        run: npm install
      - name: Build
        run: npm run build
      # 查看 workflow 的文档来获取更多信息
      # @see https://github.com/crazy-max/ghaction-github-pages
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          BRANCH: gh-pages
          FOLDER: docs/.vuepress/dist
          fqdn: b.li543.eu.org
